### ISSUE TITLE
nomor dengan awalan 08

### ISSUE THREAD

**Issue by 94maldini** [mimamch/wa-gateway#18]
kenapa tidak suport 08? saya coba sesalu time out
```shell
Error: Timed Out
    at E:\Maldini\node\wa-gateway-master\node_modules\@whiskeysockets\baileys\lib\Utils\generics.js:159:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (E:\\Maldini\\node\\wa-gateway-master\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\generics.js:154:19)\n' +
      '    at waitForMessage (E:\\Maldini\\node\\wa-gateway-master\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:116:61)\n' +
      '    at query (E:\\Maldini\\node\\wa-gateway-master\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:139:22)\n' +
      '    at getUSyncDevices (E:\\Maldini\\node\\wa-gateway-master\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\messages-send.js:166:30)\n' +
      '    at E:\\Maldini\\node\\wa-gateway-master\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\messages-send.js:347:53\n' +
      '    at Object.transaction (E:\\Maldini\\node\\wa-gateway-master\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:136:32)\n' +
      '    at relayMessage (E:\\Maldini\\node\\wa-gateway-master\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\messages-send.js:276:30)\n' +
      '    at Object.sendMessage (E:\\Maldini\\node\\wa-gateway-master\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\messages-send.js:637:23)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}
GET /send-message?to=081143xxxxx&text=maldini%20test%20api%202&session=123789456 400 60401.782 ms - 53
``` 
dengan awalan 62 berjalan lancar. saya liat di processNumber harusnya bisa

**Comment by mimamch** [comment]
Pada api terbaru, nomor tujuan wajib menyertakan kode negara. Coba dilihat lagi apakah nomor tujuannya diproses oleh fungsi processNumber atau tidak, karena di versi terbaru nomor tujuan sudah tidak melewati fungsi processNumber.
